### ISSUE TITLE
Need to have a more graceful error message for when the version is not supported by the server.

### ISSUE THREAD

**Issue by llliuwg** [hashmapinc/witsml-client#5]
Trying to connect to https://witsml.us.pason.com/hub/witsml/store but got this error:

ERROR StatusLogger No log4j2 configuration file found. Using default configuration: logging only errors to the console. Set system property 'org.apache.logging.log4j.simplelog.StatusLogger.level' to TRACE to show Log4j2 internal initialization logging.
Exception in thread "main" java.lang.IllegalArgumentException: Requested version not supported by the server
        at com.hashmapinc.tempus.witsml.client.Client.connect(Client.java:155)
        at com.hashmapinc.tempus.witsml.example.MyWitsmlClient.main(MyWitsmlClient.java:56)

**Comment by llliuwg** [comment]
With version 1.3.1.1, it can connect. So close this issue.

**Comment by cherrera2001** [comment]
Although this issue is closed, we need to have a more graceful error message. So I will reopen this to fix the message.

**Comment by cherrera2001** [comment]
The change was made to provide the error message that describes what the supported versions are.

**Comment by cherrera2001** [comment]
fix PR 6
